# Generated by Django 6.0.5 on 2026-06-05 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('fleet', '0004_remove_vehicle_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='assigned_driver',
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': ['ADMIN', 'SUPERADMIN'], 'profile__role_approved': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
