# Generated by Django 6.0.5 on 2026-06-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_assigned_driver'),
        ('branch', '0002_rename_branchinfo_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_branch', to='branch.branch'),
        ),
    ]
