# Generated by Django 6.0.5 on 2026-06-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_assigned_driver_and_more'),
        ('driver', '0003_dispatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='driver.driverprofile'),
        ),
    ]
