# Generated by Django 6.0.5 on 2026-06-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_choice',
        ),
    ]
