# Generated by Django 6.0.5 on 2026-06-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_current_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
    ]
