# Generated by Django 6.0.5 on 2026-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_dispatches_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatches',
            name='dispatch_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
