# Generated by Django 6.0.5 on 2026-06-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driverprofile_license_number'),
        ('fleet', '0002_remove_vehicle_vehicle_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AssignedVehicle', to='driver.driverprofile'),
        ),
    ]
