# Generated by Django 6.0.5 on 2026-06-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('profile', '0002_alter_profile_approved_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchInfo',
            new_name='Branch',
        ),
    ]
