# Generated by Django 6.0.5 on 2026-06-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_dispatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatches',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='driver.driverprofile'),
        ),
    ]
