# Generated by Django 6.0.5 on 2026-07-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_dispatchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='route_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
