# Generated by Django 6.0.5 on 2026-07-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_dispatchrecord_route_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='distance_traveled_km',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
