# Generated by Django 6.0.5 on 2026-07-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_add_distance_traveled_km_to_dispatchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
