# Generated by Django 6.0.5 on 2026-07-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driverprofile_is_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
