# Generated by Django 6.0.5 on 2026-06-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['super admin', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to='profile.profile'),
        ),
    ]
